version: '2'
services:
  app:
    restart: always
    mem_limit: 512m
    command: node --max_old_space_size=150 app
    image: build-atendimento-backend
    volumes:
      - /filesystem/atendimento-backend/logs:/usr/src/atendimento-backend/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8090
    env_file:
      - compose.env

  filebeat:
    build:
      context: ./filebeat
      dockerfile: ./Dockerfile
    mem_limit: 128m
    restart: always
    command: filebeat -e -strict.perms=false -path.config /usr/share/filebeat
    volumes_from:
      - app
    volumes:
      - /etc/localtime:/etc/localtime:ro

  lb:
    restart: always
    mem_limit: 128m
    image: dockercloud/haproxy
    ports:
      - 8094:80
      - 1938:1936
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MAXCONN: 20000